-- =====================================================
-- AI Mail Agent - Initial Seed Data
-- =====================================================
-- This script inserts initial data for development/testing.
-- Run after: 01-schema.sql
-- =====================================================

-- =====================================================
-- Default Admin User
-- =====================================================
-- Password: admin123! (hashed with bcrypt)
-- Note: In production, change this password immediately!

INSERT INTO users (email, name, password_hash, password_salt, is_admin, is_active)
VALUES (
    'admin',
    'Admin User',
    -- This is a placeholder hash. The actual hash will be generated by the application.
    -- The backend will regenerate this on first startup if ADMIN_BOOTSTRAP_ENABLED=true
    NULL,
    NULL,
    TRUE,
    TRUE
) ON CONFLICT (email) DO NOTHING;

-- =====================================================
-- Sample Organizations (Optional)
-- =====================================================

INSERT INTO organizations (name, level, sort_order) VALUES
    ('本社', 1, 1),
    ('営業本部', 2, 2),
    ('開発本部', 2, 3),
    ('管理本部', 2, 4)
ON CONFLICT DO NOTHING;

-- =====================================================
-- Sample Email Templates (Optional)
-- =====================================================
-- These will be created for the admin user

DO $$
DECLARE
    admin_id INTEGER;
BEGIN
    SELECT id INTO admin_id FROM users WHERE email = 'admin' LIMIT 1;

    IF admin_id IS NOT NULL THEN
        -- 会議招集テンプレート
        INSERT INTO email_templates (user_id, name, category, subject, body, variables)
        VALUES (
            admin_id,
            '会議招集',
            '社内連絡',
            '【会議招集】{{meeting_title}}',
            E'各位\n\nお疲れ様です。\n\n下記の通り会議を開催いたします。\nご参加をお願いいたします。\n\n【会議名】{{meeting_title}}\n【日時】{{date}} {{time}}\n【場所】{{location}}\n【議題】\n{{agenda}}\n\n以上、よろしくお願いいたします。',
            '["meeting_title", "date", "time", "location", "agenda"]'::jsonb
        ) ON CONFLICT DO NOTHING;

        -- 勤怠連絡テンプレート
        INSERT INTO email_templates (user_id, name, category, subject, body, variables)
        VALUES (
            admin_id,
            '勤怠連絡',
            '勤怠管理',
            '【勤怠連絡】{{date}} {{type}}',
            E'上長各位\n\nお疲れ様です。\n\n勤怠について以下の通りご連絡いたします。\n\n【日付】{{date}}\n【種別】{{type}}\n【理由】{{reason}}\n\n以上、よろしくお願いいたします。',
            '["date", "type", "reason"]'::jsonb
        ) ON CONFLICT DO NOTHING;

        -- お礼メールテンプレート
        INSERT INTO email_templates (user_id, name, category, subject, body, variables)
        VALUES (
            admin_id,
            'お礼メール',
            '社外連絡',
            '【御礼】{{subject}}',
            E'{{company_name}}\n{{name}}様\n\nお世話になっております。\n\n{{content}}\n\n今後ともよろしくお願いいたします。',
            '["company_name", "name", "subject", "content"]'::jsonb
        ) ON CONFLICT DO NOTHING;
    END IF;
END $$;

-- =====================================================
-- Sample Signatures (Optional)
-- =====================================================

DO $$
DECLARE
    admin_id INTEGER;
BEGIN
    SELECT id INTO admin_id FROM users WHERE email = 'admin' LIMIT 1;

    IF admin_id IS NOT NULL THEN
        -- 通常署名
        INSERT INTO signatures (user_id, name, content, is_default)
        VALUES (
            admin_id,
            '通常',
            E'--\n管理者\nAI Mail Agent\nTEL: 03-XXXX-XXXX\nEmail: admin@example.com',
            TRUE
        ) ON CONFLICT DO NOTHING;
    END IF;
END $$;

-- =====================================================
-- Alembic Version (Mark as up-to-date)
-- =====================================================
-- This prevents Alembic from trying to run migrations on a fresh database

INSERT INTO alembic_version (version_num) VALUES ('initial_docker_setup')
ON CONFLICT DO NOTHING;

-- =====================================================
-- End of Seed Data
-- =====================================================
