// ChatInputArea.tsx
import React, { useState, useRef } from 'react';
import './ChatInputArea.css';

export type DivisionOption = { name: string; prefix: string };

type Props = {
    divisions: DivisionOption[];
    selectedDivision: string;
    setSelectedDivision: (v: string) => void;

    candidateId: string;
    setCandidateId: (v: string) => void;

    files: File[];
    setFiles: (files: File[]) => void;

    loading: boolean;
    handleUpload: () => void;
    isAutoGenerated?: boolean;
};

const ChatInputArea: React.FC<Props> = ({
    divisions,
    selectedDivision,
    setSelectedDivision,
    candidateId,
    setCandidateId,
    files,
    setFiles,
    loading,
    handleUpload,
    isAutoGenerated = false,
}) => {
    const [isDragging, setIsDragging] = useState(false);
    const fileInputRef = useRef<HTMLInputElement>(null);

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files) {
            setFiles(Array.from(e.target.files));
        }
    };

    // ✅ ドラッグ&ドロップハンドラー
    const handleDragEnter = (e: React.DragEvent) => {
        e.preventDefault();
        e.stopPropagation();
        setIsDragging(true);
    };

    const handleDragLeave = (e: React.DragEvent) => {
        e.preventDefault();
        e.stopPropagation();
        setIsDragging(false);
    };

    const handleDragOver = (e: React.DragEvent) => {
        e.preventDefault();
        e.stopPropagation();
    };

    const handleDrop = (e: React.DragEvent) => {
        e.preventDefault();
        e.stopPropagation();
        setIsDragging(false);

        const droppedFiles = Array.from(e.dataTransfer.files);
        const validFiles = droppedFiles.filter(file => 
            file.name.match(/\.(pdf|doc|docx|xls|xlsx)$/i)
        );

        if (validFiles.length !== droppedFiles.length) {
            alert('対応ファイル形式: PDF, DOC, DOCX, XLS, XLSX');
        }

        setFiles(validFiles);
    };

    const handleClickUploadArea = () => {
        fileInputRef.current?.click();
    };

    return (
        <div className="chat-input-rows">
            <div className="chat-input-row">
                <select
                    value={selectedDivision}
                    onChange={(e) => setSelectedDivision(e.target.value)}
                    className="chat-select"
                    disabled={loading}
                >
                    <option value="">希望部門を選択</option>
                    {divisions.map((d) => (
                        <option key={d.prefix} value={d.prefix}>
                            {d.name}
                        </option>
                    ))}
                </select>

                <div className="candidate-id-container">
                    <input
                        type="text"
                        placeholder={isAutoGenerated ? "自動生成されました" : "候補者IDを入力"}
                        value={candidateId}
                        onChange={(e) => setCandidateId(e.target.value)}
                        className={`chat-candidate-input ${isAutoGenerated ? 'auto-generated' : ''}`}
                        disabled={isAutoGenerated || loading}
                    />
                    {!isAutoGenerated && (
                        <button
                            type="button"
                            className="generate-id-btn"
                            onClick={() => {
                                const newId = 'cand_' + Math.random().toString(36).substring(2, 10);
                                setCandidateId(newId);
                            }}
                            disabled={loading}
                        >
                            🔄 自動生成
                        </button>
                    )}
                </div>
            </div>

            <div className="chat-input-row second-row">
                {/* ✅ ドラッグ&ドロップエリア */}
                <div 
                    className={`file-upload-container ${isDragging ? 'dragging' : ''} ${files.length > 0 ? 'has-files' : ''}`}
                    onDragEnter={handleDragEnter}
                    onDragLeave={handleDragLeave}
                    onDragOver={handleDragOver}
                    onDrop={handleDrop}
                    onClick={handleClickUploadArea}
                >
                    <input 
                        ref={fileInputRef}
                        type="file" 
                        multiple
                        accept=".pdf,.doc,.docx,.xls,.xlsx"
                        onChange={handleFileChange}
                        disabled={loading}
                        style={{ display: 'none' }}
                    />

                    {files.length === 0 ? (
                        <label className="custom-file-upload">
                            📎 ファイルをドラッグ&ドロップ または クリック
                        </label>
                    ) : (
                        <div className="file-list">
                            <strong>選択中: {files.length}件</strong>
                            {files.map((file, index) => (
                                <span key={index} className="file-name">
                                    📄 {file.name}
                                </span>
                            ))}
                        </div>
                    )}
                </div>

                <div className="send-btn-container">
                    <button 
                        onClick={handleUpload} 
                        disabled={loading || files.length === 0} 
                        className="send-btn"
                    >
                        {loading ? '処理中...' : '送信'}
                    </button>
                </div>
            </div>
        </div>
    );
};

export default ChatInputArea;